# Generated by Django 4.1 on 2022-08-31 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=50)),
                ('salary', models.PositiveIntegerField()),
                ('experience', models.PositiveIntegerField()),
            ],
        ),
    ]
